// config.ts — MegaXtoon series platform config
// Converted from PHP config.php

import type { Series } from './types';

export const SITE_NAME = 'MegaXtoon';

/**
 * Extended series type — adds optional fields used by the new dataset
 * (episode count, cast) while staying compatible with the existing
 * Series type used across home.ts / home.tsx. If your ./types.ts
 * Series interface already declares `episodes` / `cast`, you can
 * remove this intersection and just use `Series` directly.
 */
export type SeriesWithExtras = Series & {
  episodes?: number;
  cast?: string;
};

/** Generate a poster URL from series name (matches PHP posterUrl) */
export function posterUrl(name: string): string {
  // Matches the PHP posterUrl() function — uses TMDB-style poster path
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return `https://image.tmdb.org/t/p/w500/${slug}-poster.jpg`;
}

/** Generate a background image URL (matches PHP behavior) */
export function bgUrl(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return `https://image.tmdb.org/t/p/w1280/${slug}-backdrop.jpg`;
}

export const SERIES_LIST: SeriesWithExtras[] = [
  {
    slug: 'gumball',
    name: 'The Amazing World of Gumball',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '8.7',
    year: '2011',
    seasons: '6',
    genre: 'Komedi, Macera',
    description: 'Gumball Watterson ve ailesiyle Elmore şehrindeki çılgın gündelik maceralar.',
    playlist_id: 'PLC8MXDuDxrrsyqbTa9nK_gq8qmiMfR3sM',
    episodes: 240,
    cast: 'Jacob Hopkins, Terrell Ransom Jr.',
  },
  {
    slug: 'theloudhouse',
    name: 'The Loud House',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZjlkMmQ5YzItZGRmMy00NjVjLWIwYmMtMzJjM2QxM2Q1OThkXkEyXkFqcGc@._V1_.jpg',
    rating: '7.6',
    year: '2016',
    seasons: '7',
    genre: 'Komedi, Macera',
    description: '10 kardeşin ortası Lincoln Loud, kaotik ev hayatında hayatta kalmaya çalışır.',
    playlist_id: 'PLgrisE0MOLgRBNWk2cbO035kQ0hHA11HC',
    episodes: 130,
    cast: 'Asher Bishop, Grey Griffin',
  },
  {
    slug: 'ben10ultimatealien',
    name: 'Ben 10 Alien Force',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOGQ5YWFjYjItODE5OC00ZDQxLTk5ZmYtNzY0YzM4NjIyMWFlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '8.1',
    year: '2008',
    seasons: '3',
    genre: 'Aksiyon, Macera',
    description: 'Ben Tennyson 15 yaşında uzaylı tehditlerle tekrar savaşa giriyor.',
    playlist_id: 'PLD7E4B63582E0479D',
    episodes: 46,
    cast: 'Yuri Lowenthal, Ashley Johnson',
  },
  {
    slug: 'beastboy',
    name: 'Beast Boy Lone Wolf',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYzQxY2FjOWItNjc0Mi00NGNjLTg5NGYtNDBhNzdjMDBmN2Q4XkEyXkFqcGc@._V1_.jpg',
    rating: '7.4',
    year: '2023',
    seasons: '1',
    genre: 'Aksiyon, Macera',
    description: 'Yeni nesil Beyblade turnuvaları ve efsanevi X dönüşümü.',
    playlist_id: 'PLTJkpTzCerNrGfBN3Li4vR3Uegu1-TglA',
    episodes: 38,
    cast: 'Takuma Nagare, Bird Akazawa',
  },
  {
    slug: 'SpongeBobSquarePants',
    name: 'SpongeBob SquarePants Haloween',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYjJmMjBkZjMtZThiZS00Nzk3LWJlN2UtYmE5ZjkyNjJiZjgxXkEyXkFqcGc@._V1_QL75_UY281_CR1,0,190,281_.jpg',
    rating: '8.2',
    year: '1999',
    seasons: '14',
    genre: 'Komedi, Macera',
    description: 'Bikini Bottom\'da yaşayan süngerin çılgın sualtı maceraları.',
    playlist_id: 'PLShpyCq1QZaynW4FN2Nbf-XnlPz0RNV7L',
    episodes: 280,
    cast: 'Tom Kenny, Bill Fagerbakke',
  },
  {
    slug: 'RegularShowLostTapes',
    name: 'Regular Show lost Tapes',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNDY5ZTA4ZGQtMzE2Ni00YjQ1LTk4ODktZGQwYTgwYWYxNjUwXkEyXkFqcGc@._V1_.jpg',
    rating: '8.4',
    year: '2010',
    seasons: '8',
    genre: 'Komedi, Macera',
    description: 'Mordecai ve Rigby\'nin sıradan bir parkta yaşadığı olağandışı olaylar.',
    playlist_id: 'PLTQesLu3nTxsDo01ZXTZhx4Gv3WcFjvcS',
    episodes: 261,
    cast: 'J.G. Quintel, William Salyers',
  },
  {
    slug: 'AdventureTime',
    name: 'Adventure Time',
    poster_url: 'https://occ-0-753-1007.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABRV_sMrvu3tWVViD3FG-maRs7pdM01pKVjISgK7zVIeTEQTF0E0gX2VGS-crJoN5YxzYRZIZrKfCG2W26ZRo34i3acw6fdOzwkFr6YJbYufEGQM0v8be2W-M8da2L9HC.jpg?r=7fb',
    rating: '8.6',
    year: '2010',
    seasons: '10',
    genre: 'Macera, Fantezi',
    description: 'Finn ve Jake\'in Ooo Diyarı\'ndaki epik maceraları.',
    playlist_id: 'PLLIU9nFd9IrEsR2bcrJEGERa_91aYntWX',
    episodes: 283,
    cast: 'Jeremy Shada, John DiMaggio',
  },
  {
    slug: 'MutantNinjaTurtles',
    name: 'Teenage Mutant Ninja Turtles',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZTA0ZTlkMGItNTJmYy00YTVkLTgwMDktZTJiNTE5NmQ0ZWI4XkEyXkFqcGc@._V1_.jpg',
    rating: '8.0',
    year: '2012',
    seasons: '5',
    genre: 'Aksiyon, Macera',
    description: 'Dört kaplumbağa ninja New York\'u korumak için gece karanlığına çıkıyor.',
    playlist_id: 'PL9FtL6eB-Npz_3om-MWlUXWQ87eWzaxl9',
    episodes: 124,
    cast: 'Sean Astin, Greg Cipes',
  },
  {
    slug: 'TransformersEarthSpark',
    name: 'Transformers EarthSpark',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNjAxNmRhZjctYTk1Ni00MGJjLThkY2YtNjdmODJjYTMwOGJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.2',
    year: '2022',
    seasons: '2',
    genre: 'Aksiyon, Sci-Fi',
    description: 'Dünyada doğan ilk Terran Transformers ile insanlığın yeni bir birlikteliği.',
    playlist_id: 'PL7VEq3tXc6hsvHKfzdknf8GViPEr5JW5W',
    episodes: 26,
    cast: 'Zeno Robinson, Sydney Mikayla',
  },
  {
    slug: 'Ninjago',
    name: 'Ninjago',
    poster_url: 'https://ninjagoizlesene.com.tr/wp-content/uploads/2026/03/Crystalized-Poster-scaled.jpg',
    rating: '7.8',
    year: '2011',
    seasons: '15',
    genre: 'Aksiyon, Macera',
    description: 'Spinjitzu ustası Garmadon\'a karşı savaşan dört ninjanın destanı.',
    playlist_id: 'PLwf-K0eNy8ANtvsRvluuNfPIEd3db5r8k',
    episodes: 200,
    cast: 'Vincent Tong, Michael Adamthwaite',
  },
  {
    slug: 'gravityfalls',
    name: 'Gravity Falls',
    poster_url: 'https://m.media-amazon.com/images/I/917WCiqRo6L._AC_UF1000,1000_QL80_.jpg',
    rating: '8.9',
    year: '2012',
    seasons: '2',
    genre: 'Gizem, Komedi',
    description: 'Dipper ve Mabel\'in büyükannesinin yanında geçirdikleri paranormal yaz tatili.',
    playlist_id: 'PL5VwaAJ3JDSHr9ZnkEgu8GLC_x1JxrPcc',
    episodes: 40,
    cast: 'Jason Ritter, Kristen Schaal',
  },
  {
    slug: 'stevenuniverse',
    name: 'Steven Universe',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZGJjMmI3ZDMtZTgyNi00MTZhLWE2ZjAtN2Q4YTUyMTg4OGY1XkEyXkFqcGc@._V1_.jpg',
    rating: '8.2',
    year: '2013',
    seasons: '5',
    genre: 'Macera, Müzikal',
    description: 'Yarı insan yarı Kristal Mücevher olan Steven\'ın dünyayı kurtarma yolculuğu.',
    playlist_id: 'PLIw4JuB69kRqSaga1p7kzPx99UOgrvRMA',
    episodes: 160,
    cast: 'Zach Callison, Estelle',
  },
  {
    slug: 'FairlyOdd',
    name: 'The Fairly OddParents',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BY2RlNWMwZmUtMjM4MC00MDczLTk3NjktYTg2OTNiNThhNmNhXkEyXkFqcGc@._V1_.jpg',
    rating: '7.5',
    year: '2001',
    seasons: '10',
    genre: 'Komedi, Fantezi',
    description: 'Timmy Turner\'ın peri vaftiz anne babaları ile yaptığı dilekler hep çığırından çıkıyor.',
    playlist_id: 'PLZb1SVCX0ajoclQynrUz26jQm3aJ7Y0uS',
    episodes: 172,
    cast: 'Tara Strong, Daran Norris',
  },
  {
    slug: 'clarence',
    name: 'Clarence',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg',
    rating: '7.4',
    year: '2014',
    seasons: '3',
    genre: 'Komedi, Macera',
    description: 'Aşırı iyimser çocuk Clarence\'ın sıradan gündelik hayatın tadını çıkaran maceraları.',
    playlist_id: 'PLg6KfZlgBuDVJM8_fYqLiBivHRmsu_lOj',
    episodes: 121,
    cast: 'Spencer Rothbell, Tom Kenny',
  },
  {
    slug: 'mira',
    name: 'Miraculous Ladybug',
    poster_url: 'https://image.tmdb.org/t/p/w500/mwAJcSPtuRddU8AeL9lup5jE0Bn.jpg',
    rating: '7.6',
    year: '2015',
    seasons: '5',
    genre: 'Macera, Romantik',
    description: 'Paris\'i koruyan iki genç kahraman — Ladybug ve Cat Noir.',
    playlist_id: 'PLaMHyq8hhBW1o-vm10TyFjxtjNG2po9ze',
    episodes: 130,
    cast: 'Cristina Vee, Bryce Papenbrook',
  },
  {
    slug: 'codename',
    name: 'Codename: Kids Next Door Shorts',
    poster_url: 'https://www.tvtime.com/_next/image?url=https%3A%2F%2Fartworks.thetvdb.com%2Fbanners%2Fposters%2F71685-2.jpg&w=640&q=75',
    rating: '7.7',
    year: '2002',
    seasons: '6',
    genre: 'Komedi, Macera',
    description: 'Beş çocuktan oluşan gizli ajan ekibi yetişkinlere karşı savaşıyor.',
    playlist_id: 'PL258poKABt5XHZ4aHMIRme6M9ichpplwg',
    episodes: 78,
    cast: 'Benjamin Diskin, Rachael MacFarlane',
  },
  {
    slug: 'circus',
    name: 'The Amazing Digital Circus',
    poster_url: 'https://fr.web.img5.acsta.net/c_310_420/img/e0/d1/e0d113764c9c629f20a681041ab4e01c.jpg',
    rating: '8.3',
    year: '2023',
    seasons: '1',
    genre: 'Komedi, Gizem',
    description: 'Dijital bir sirkde mahsur kalan insanların var olmaya çalışması.',
    playlist_id: 'PLHovnlOusNLgvAbnxluXCVB3KLj8e4QB-',
    episodes: 6,
    cast: 'Lizzie Freeman, Michael Kovach',
  },
  {
    slug: 'sonicprime',
    name: 'Sonic Prime',
    poster_url: 'https://preview.redd.it/what-makes-sonic-prime-forgettable-than-the-other-sonic-v0-vka3qbs2w7ye1.png?width=640&crop=smart&auto=webp&s=3dd7cbb9b2bacdd621b34b37d25904ca536ab061',
    rating: '6.9',
    year: '2022',
    seasons: '3',
    genre: 'Aksiyon, Macera',
    description: 'Sonic çoklu evrende yolculuk ederek arkadaşlarını ve Shatterverse\'ü kurtarıyor.',
    playlist_id: 'PLl5oejYNsf65FB-cWNS2JKsXWyEobLszM',
    episodes: 24,
    cast: 'Deven Mack, Brian Drummond',
  },
  {
    slug: 'ttg',
    name: 'Teen Titans Go!',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjE5MjMzOTc1Ml5BMl5BanBnXkFtZTcwNDQxMDY5OQ@@._V1_FMjpg_UX1000_.jpg',
    rating: '5.8',
    year: '2013',
    seasons: '8',
    genre: 'Komedi, Aksiyon',
    description: 'Teen Titans\'ın gündelik kahramanlık dışı komik maceralarını anlatan spin-off.',
    playlist_id: 'PLd3-CCCcbQeKcs5A_b8x45cTjZ0TFk-yn',
    episodes: 350,
    cast: 'Greg Cipes, Scott Menville',
  },
  {
    slug: 'kiff',
    name: 'Kiff',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjA1NjIwNTMtY2Q2Ny00ZmVjLThkODItODg1ZjJmN2FjMDUzXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2020',
    seasons: '2',
    genre: 'Komedi',
    description: 'Bir ortaokul öğrencisinin maceraları.',
    playlist_id: 'PLCGQDmE5nVHriQOifbcVibE_gKshXJIhd',
    episodes: 20,
    cast: 'Kiff, Kiff',
  },
  {
    slug: 'tomandjerry',
    name: 'Tom and Jerry',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BODY2YWI1OTAtY2FhZS00MGI1LTk0YjUtYmE3MDk0OGFkMWUyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '8.7',
    year: '1940',
    seasons: '1',
    genre: 'Komedi',
    description: 'Kedi Tom ve fare Jerry arasındaki hiç bitmeyen kovalamaca.',
    playlist_id: 'PLeWt4i89tkloEBo3eyC_ZKKNrwL277eG_',
    episodes: 161,
    cast: 'William Hanna, Joseph Barbera',
  },
  {
    slug: 'batmanunlimited',
    name: 'Batman Unlimited',
    poster_url: 'https://play-lh.googleusercontent.com/RWN0fec0a0lc8Y-VBfDHcnN-L3OrwE-xcu3SN0dQ8UWrdpn_B-LI0OxnHOKXZysB5hPZ',
    rating: '7.2',
    year: '2010',
    seasons: '1',
    genre: 'Aksiyon, Animasyon',
    description: 'Batman\'ın ve diğer super kahramanların maceraları.',
    playlist_id: 'PLLDIqfKdBJnOcW48eRV9A0sweGS-Ex8NM',
    episodes: 10,
    cast: 'James Arnold Taylor, Maryke Hendrikse',
  },
  {
    slug: 'thundermans',
    name: 'The Thundermans',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMzUyNzE2NTgtNzM0Ny00YzBjLWJmZjAtMmMwYmE5YTg1MjEyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '6.8',
    year: '2013',
    seasons: '4',
    genre: 'Komedi, Aksiyon',
    description: 'Süper güçlere sahip Thunderman ailesinin sıradan görünmeye çalıştığı hayatı.',
    playlist_id: 'PLOmUMd_oRO0uFCW9fmB8RrqF7lgOtN0p4',
    episodes: 97,
    cast: 'Kira Kosarin, Jack Griffo',
  },
  {
    slug: 'ltunescartoons',
    name: 'Looney Tunes Cartoons',
    poster_url: 'https://m.media-amazon.com/images/I/71lg8c9EZeL._AC_UF894,1000_QL80_.jpg',
    rating: '7.9',
    year: '2019',
    seasons: '5',
    genre: 'Komedi',
    description: 'Bugs Bunny, Daffy Duck ve diğer sevilen karakterlerin yeni kısa animasyonları.',
    playlist_id: 'PL1Z6ttYZJTaMqSFfkTZDwQFt3Xpgodu2W',
    episodes: 200,
    cast: 'Jeff Bergman, Bob Bergen',
  },
  {
    slug: 'clarenceromania',
    name: 'Clarence Romania',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2022',
    seasons: '3',
    genre: 'Aksiyon, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLRbdoUts81DWI8w7bcqNZdeUVgMx0890x',
    episodes: 106,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'scooby',
    name: 'Scooby Show',
    poster_url: 'https://licensing.biz/wp-content/uploads/2023/10/Scoobtober-569x1024.jpg',
    rating: '7.8',
    year: '2022',
    seasons: '1',
    genre: 'Aksiyon, Gizem korku',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLTOeHiCTiZp1b7AlWiE4amd9AMRBMC',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'haloween',
    name: 'CN Halloween Special',
    poster_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNuhPN8CJpb-jtexxFyvoq2Fi8pT6dD1vqPA&s',
    rating: '7.8',
    year: '2022',
    seasons: '1',
    genre: 'Aksiyon, Gizem korku',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLJRBd5RNL15EJD1ELg9HiUcYP6_rhaqWK',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'regularshow',
    name: 'Regular Show',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNDJlMGI1MDYtZDM0MS00NDYzLWIyMmUtZTY5MjY3MzJiN2QwXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Aksiyon, komedisi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLaj5S0F-5Vr-eQzftZnrC8spAfwZo1JQO',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'flapjack',
    name: 'FlapJack',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTkzMDdiNGItYmZmYy00NDU0LWE5ZDMtZTgyNDc3ODgzNzM2XkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLkZ1r2KIV0fzUuG1EWlvXEYFiX5By02h2',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'gumball',
    name: 'Gumball',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLiR6LEIR8I0AeNLmoEbplwzELDMl6zaKu',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'ppg',
    name: 'Power Puff Girls',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMDI5NmQwZTUtNWI0Mi00MDE2LTkwNzQtMDFmZjRkM2Y1YjEwXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PL258poKABt5Wx-YXePg6WfdKopiXxbibb',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'chowder',
    name: 'Chowder',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_QL75_UY281_CR13,0,190,281_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PL258poKABt5V6PzpqnlqD0aM937YU1bmq',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'cnhalloween',
    name: 'CN Halloween Time',
    poster_url: 'https://i.ebayimg.com/images/g/wXUAAOxyxU1Q9FlH/s-l640.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem korku',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PL258poKABt5XNOWoAtRCQJKBMKAWMRdsQ',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'billyandmandy',
    name: 'The Grim Adventures of Billy and Mandy',
    poster_url: 'https://i.redd.it/v05l6wted5071.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem korku',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLaK542wd-ut4O8KRF1aumS4GLa1AoBvSE',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'spongebob',
    name: 'SpongeBob SquarePants',
    poster_url: 'https://image.tmdb.org/t/p/original/zDuKxQkG8EemvLdBn43ChdM0MJL.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLXG4I392sUnODI37L4o1tp9SSu-oxTPAF',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'transformerscyber',
    name: 'Transformers: Cyberverse',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTdkMDZiNjgtNGI0Yi00MmFmLTgyNzEtNTdmYjc3OWU3Y2I2XkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Aksiyon',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLiz2R-QaHSOt2tN9F8gmGL2vRHYGNQr-M',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'couragethecowardlydog',
    name: 'Courage the Cowardly Dog',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNDJiYjJlZTctYmFkMy00MDE0LTgyYmYtZTg3NjViZmY3MDc4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Gizem korku',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLiz2R-QaHSOt58OUAucix0rxJ2OR9-ssc',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'phineas',
    name: 'Phineas and Ferb',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTc1NjcxNzg4MF5BMl5BanBnXkFtZTgwOTMzNzgyMDE@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLHBUmMjK-bVeW2PaKLYIiuY7h1FSP81NQ',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'yellowyeti',
    name: 'De Geweldige Yellow Yeti',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZDdjOTY2OTktMjdhMy00NTU1LTllZDktNTkzMDQyNTVkMjZmXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLHBUmMjK-bVdeDry56-lwTOTOUOlYV0pg',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'geestmolly',
    name: 'De Geest en Molly McGee',
    poster_url: 'https://static.filmvandaag.nl/shows/original/9000/9302.jpg?v=1&width=400',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLHBUmMjK-bVdc_wyjWNHtn0VhZ-SQXTfM',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'stevenfuture',
    name: 'Steven Universe: Future',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZTAxMTY1ZDAtMmY0Yy00Mzk1LTk3MzItZTA3YjM1NTMxMmRiXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLnnhPWO60cimwgwboYyB_1YIFQ5auCLTz',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'chowder',
    name: 'Chowder',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLLIU9nFd9IrE8gglrM_S7Js2OPqyk5eO_',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'villainous',
    name: 'Villainous',
    poster_url: 'https://upload.wikimedia.org/wikipedia/en/5/5c/VillainousMiniseriesOriginalCover.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLx4owGbSBUxrv1Lb81k_i23RY2WwtDZ-Z',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'randy',
    name: 'Randy Cunningham: Nastoletni Ninja',
    poster_url: 'https://images.justwatch.com/poster/207531981/s718/randy-cunningham-9th-grade-ninja.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLlLYYUTQfvu00CD-uaQ3gwXTckKskq7Pu',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'kick',
    name: 'Kick Buttowski',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZTk3OGMwMWMtOWYwYS00MjUzLWJlY2EtNzUyOWExYmQ2ZTQ1XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLE9ABE6A4D20BD9FD',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'ultimate',
    name: 'Ultimate Spider-Man',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjFmOGZkYWQtMGQ4MC00NzRiLWI4ZTMtNDEwZDZiMDMyMzNmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PL9qXF14Xc9gLPJplbj-JXTJDgffVP2VZL',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'galaxy',
    name: 'Guardians of the Galaxy',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNDM4NDQxMDU2MV5BMl5BanBnXkFtZTgwMDY2MDQ5NjE@._V1_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PL9qXF14Xc9gLFaK97EYwqmjoZc7g_-8z9',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'bighero',
    name: 'Big Hero 6',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOTc3YTYwNTQtNzNmOC00YTg1LWJiNTgtYWU0ZjgyMzRjNDc2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PL9qXF14Xc9gJ8NTJanihD2kCa3jXPQHqx',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'ducks',
    name: 'La Bande à Picsou',
    poster_url: 'https://fr.web.img4.acsta.net/pictures/20/03/16/16/57/5441696.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLFCwHVG6gilNP-YQzgD9YPOU5nmlDO-UQ',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'bigdinasour',
    name: 'Moon Girl et Devil le Dinosaure',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMzViMTQ5ZGYtMmRjZC00OTVjLTkzMTEtMGMxMzlkNDc1OGQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLFCwHVG6gilNLwChC5ZNs_7XlZ1Jcanqw',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'ghostforce',
    name: 'Ghost Force',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZGE3MDQ3OGEtMDEwMS00YTE3LWE1Y2YtZGFiYzE2MWU4Nzg5XkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2015',
    seasons: '1',
    genre: 'Macera, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLFCwHVG6gilP8m34GhDrS8ROablGcE4_T',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'distandlands',
    name: 'Adventure Time: Distant Lands',
    poster_url: 'https://resizing.flixster.com/DyT34YI3TO_5fp_CPLof6WUor-c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjkyMjk2Mi53ZWJw',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLmEWbcIX2pqr1ia5IvNpukZiVGKvDOG5M',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'angelo-rules',
    name: 'Angelo Rules',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZTU4YWRlMTUtMWFmZS00ZDMzLTgwM2YtNjgwOTQ0ODA3MmRmXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLEskFgfTPJn3E1kMX2RLhB5TsLrfpkLlK',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'maxs',
    name: 'Max & The Midknights ',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYjJiMTM4ZjUtMDMzNi00NTAxLThhOTktNTk3M2IwNTQxYzJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLUQR09yEYrP19UtlDyc4-mNC1eGyy-VtX',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'generator-rex',
    name: 'Generator Rex',
    poster_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAA801bMLg1gxTDY9vVIW3tEyl3dP58n-KOQ&s',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLeWt4i89tklqXah-0HBdGhszq__G0Eozb',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'fosters',
    name: 'Foster home for imaginary friends',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PL8ImJqzk7DAaA9mTiBYXh0Vs1oz9b3W2z',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'starwarsresistance',
    name: 'Star Wars: The Resistance',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTkyMTc3NjAwNF5BMl5BanBnXkFtZTgwNTU1ODIyNjM@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLXsbMnnbPpLUQmff9_ReAk8g8u92_6rJd',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'teentitans',
    name: 'Teen Titans',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOTg3NzY2MDQtMjUxNS00N2Q3LTkxODktMmU1NzdjZTNkMzQ0XkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLhiban91e2OqgVt6dccVkJ07t3bFv7uOx',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'minecraft story mode',
    name: 'Minecraft Story Mode',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZWNkN2NjNzUtMWU5OC00Mzk5LThlM2YtODJkYjdhNDFlOTQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLLsCJcWF3vVeGCgvvN06UbvT5IVXjHknN',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'beavis',
    name: 'Beavis and Butt-Head',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNzU3Mzk0ZTUtMmRkNS00MjI1LWEzNjYtNzI2MWJkN2JkNjc4XkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLLHHcQWkLnprz8QqcuoNJ3apW2vsj0v8D',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'simpsons',
    name: 'The Simpsons',
    poster_url: 'https://images.justwatch.com/poster/307635545/s332/sezon-35.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem, Yaz Vakti',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLCVuwQ1eXVCWbQ06SrBiCZlB1Ci6qJdFw',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'naruto',
    name: 'Naruto',
    poster_url: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic0.cbrimages.com%2Fwordpress%2Fwp-content%2Fuploads%2Fsharedimages%2F2024%2F07%2Fnaruto-2002.jpg%3Fq%3D49%26fit%3Dcontain%26w%3D480%26dpr%3D2&f=1&nofb=1&ipt=cb82e0178d6ca5c988934b1864ad147a23f58079b0afa1ed628505d28cb3fd59',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem, Yaz Vakti',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLj_3vEvEUBsPifJi6PFSf7oQMYMs02smw',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'beybturbo',
    name: 'Beyblade Turbo',
    poster_url: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fih1.redbubble.net%2Fimage.2941796449.3180%2Fflat%2C750x%2C075%2Cf-pad%2C750x1000%2Cf8f8f8.jpg&f=1&nofb=1&ipt=2d8a8bc514ddc7286d7a54473b5c1801543f9016432bb718167081719b0d35c3',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem, Yaz Vakti',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLULgaql63Wf4Kv1R1MjgMCyLimH1fAMqY',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'robotchicken',
    name: 'Robot Chicken',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNmMxZWM5NzYtMTJkNS00YTA1LWE2MzYtNmI0NTQzOTRmODQ0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem, Yaz Vakti',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLG8ENTVyb-dfY_bOaciqr6bsXsKZq61_9',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'rickandmortysimpsons',
    name: 'Rick and Morty - Simpsons Universe Special',
    poster_url: 'https://mir-s3-cdn-cf.behance.net/project_modules/fs/e8cd9488239301.5dd0486ee11eb.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLhSgw0LS-Vy9wvGRTJADhiOrlCAjNCMAN',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'familyguy',
    name: 'Family Guy',
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNTZlMGQ1YjEtMzVlNC00ZmMxLTk0MzgtZjdkYTU1NmUxNTQ0XkEyXkFqcGc@._V1_.jpg',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLd3-CCCcbQeJ4A0MXjaOk3C_1ABIN3ICM',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'pokemon',
    name: 'Pokémon',
    poster_url: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F57c7ed67-f9d0-47a8-82dc-7506d8128ea8%2Fdc3k9hx-bd8d5811-2cf9-4a0c-b266-986f375e4797.png%2Fv1%2Ffill%2Fw_777%2Ch_1029%2Cq_70%2Cstrp%2Fmy_pokemon_poster_gen_1_by_supermariocarlos_dc3k9hx-pre.jpg%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTM1NiIsInBhdGgiOiJcL2ZcLzU3YzdlZDY3LWY5ZDAtNDdhOC04MmRjLTc1MDZkODEyOGVhOFwvZGMzazloeC1iZDhkNTgxMS0yY2Y5LTRhMGMtYjI2Ni05ODZmMzc1ZTQ3OTcucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.kEyd8On5ohDzew3M24hFeSbDBPiPeur24TVT8A11nbc&f=1&nofb=1&ipt=9f794c9ff5846a0a60531b0309792481da42978b84c4ab324fd2dc655d3cadf5',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Yaz Vakti',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLo60BvbiWBuqUwSRFou3pbPV2IAWaP0rg',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'pokemonrevizon',
    name: 'Pokémon Reizen minisode',
    poster_url: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.pokemonunited.nl%2Fwp-content%2Fuploads%2FANI_S25_Key_Art_NL-scaled.jpg&f=1&nofb=1&ipt=eaf26f0fe39cea9a5f2be88e16058cc8af5a276c26eb64deb9d92050d151110e',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Macera, Yaz Vakti',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLv8gpXY5S5ljQScHua3FRjGVJ6XLeXh_i',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'peanuts',
    name: 'Peanuts',
    poster_url: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.justwatch.com%2Fposter%2F287913782%2Fs718%2Fdie-peanuts-classics.jpg&f=1&nofb=1&ipt=0adacddeb994d749ee4d953a3c7304b517eda939edf0b7bb40393889d9e92565',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Yaz Vakti, Komedi',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLLhOnau-tupQarwF3RjxwUV8Kr6UZONjv',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'scooby-doo',
    name: 'Scooby-Doo mysteries',
    poster_url: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FjuYcNvxsktoTgBL0qaNNYqvhj8K.jpg&f=1&nofb=1&ipt=5db4bb41091ac7e8ce27da053190352ffc74b22277657c5706a3180deb45690d',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Yaz Vakti, Komedi,Gizem',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLhDDUaSrgZ2vk1Cn8polKKw6N9V9WVuDV',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'nicktoons',
    name: 'NickToons Collection',
    poster_url: 'https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/014963da899bbbab049e5b228b426196/KOLEKSIYONU-4.png',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Koleksiyon',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLJb1AL9zU1Gpmo3_TKD7mG4MmzuhuPE0d',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
  {
    slug: 'cartoonnetwork',
    name: 'Cartoon Network Collection',
    poster_url: 'https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/706be073ad50f9598c060a6223217220/KOLEKSIYONU-3.png',
    rating: '7.8',
    year: '2010',
    seasons: '1',
    genre: 'Koleksiyon',
    description: 'Desire Grand Prix\'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.',
    playlist_id: 'PLZjNMNd2gTe5E6VQR04WVBsjvkDzVUBpw',
    episodes: 49,
    cast: 'Ryuga Sato, Mio Kudo',
  },
];

/** Find a series by its URL slug. */
export function getSeriesBySlug(slug: string): SeriesWithExtras | undefined {
  return SERIES_LIST.find((s) => s.slug === slug);
}
